### ISSUE TITLE
Word Boundaries by Default on Extra Mentions

### ISSUE THREAD

**Issue by arkham81a** [CBenni/mt2#12]
When adding Custom Mentions they have no word boundaries by default. So whenever I had the word "Mod" added in words like Promod & Modding were highlighted. If you know anything about regex you can add them in yourself with \b but they should be there by default.

**Comment by CBenni** [comment]
This has the issue that if you dont want word boundaries, you cant opt out of them, if I always add them. If you have a suggestion for this, im happy to hear. I might revamp the extra mentions system later down the path

**Comment by xhip** [comment]
🤔 can't you do it, like https://regexr.com/ they select the words affected by the regex, would be nice to have something like that.
