### ISSUE TITLE
Notifications for Mentions in Non-Active Chats

### ISSUE THREAD

**Issue by arkham81a** [CBenni/mt2#13]
Whenever having one chat behind another they stack up into tabs and it's really easy to make viewers think you're ignoring their mentions as you still show up on the Viewer-list. My suggestion would to have the Tab itself highlight if it has had a highlighted word said in it when it's inactive.

Concept Art Below. 

![concept](https://user-images.githubusercontent.com/35945634/38980116-fa02df08-4389-11e8-8808-f71efd31f0e1.png)

**Comment by atum92** [comment]
As an added suggestion into this feature, including a sound whenever you are mentioned in any chat would be grateful.

**Comment by CBenni** [comment]
I fixed this in yesterdays deploy
