### ISSUE TITLE
Condensed Modlogs

### ISSUE THREAD

**Issue by arkham81a** [CBenni/mt2#14]
Modlogs for what appears to be random timeouts (About 30% of them) only show info on who preformed the timeout, not showing Timeout length or Reason. 

Attached below is a Screenshot of the Log from MT2 On top of the actual timeout from the Logviewer

![untitled-1](https://user-images.githubusercontent.com/35945634/38983793-3cc1a3fc-4393-11e8-9ee7-54984ca64120.png)

**Comment by arkham81a** [comment]
It seems to have also become more common. I'm seeing less and less Timeout times/reasons. https://i.imgur.com/9JUQh5v.png

**Comment by CBenni** [comment]
should be fixed, lmk if it happens once the build is up
