### ISSUE TITLE
Lengthen Mod Logs Hover Time

### ISSUE THREAD

**Issue by DoctorWigglez** [CBenni/mt2#16]
Currently when you highlight a mod log to see why someone was timed out, any time a new message comes into the chat, the tooltip box that pops up describing this reason fades out (even when the line itself for the mod log doesn't move)

![](https://i.imgur.com/1IPBizS.png)

**Comment by CBenni** [comment]
Theres some issue with tooltips in general, will have to look into that, thanks

**Comment by CBenni** [comment]
This seems to be a behavior of angular-material that has no easy fix. Perhaps I will attempt to fix this in the future, but ill push it back for unproportional effort for now.
