### ISSUE TITLE
Percise Matches

### ISSUE THREAD

**Issue by arkham81a** [CBenni/mt2#18]
Precise matches appear to be looking for exact matches in the title over the Channel name

Example - https://i.imgur.com/qrANw1p.gifv

**Comment by arkham81a** [comment]
And current errors. 
https://i.imgur.com/llPzw14.png
https://i.imgur.com/5elYOZ9.png
https://i.imgur.com/USb5FtE.png
https://i.imgur.com/at88ZKR.png
https://i.imgur.com/fYzLQxB.png
https://i.imgur.com/yEE1ay8.png

**Comment by CBenni** [comment]
Those errors are whispers btw, fixing those right now.
