### ISSUE TITLE
Implement "multiple pages"

### ISSUE THREAD

**Issue by xhip** [CBenni/mt2#19]
Adding the concept of **pages**, so I could add my main chats on the **first page** and maybe add the not so active ones to the **other page**. This way I still can keep an eye on them from time to time and also receiving "mentions" if something happens.

If you need more details, please DM me

**Comment by arkham81a** [comment]
Similar to having multiple desktops in Windows 10 or Sheets in Excel, where you could pretty much have a whole window of mod chat in another tab.

**Comment by CBenni** [comment]
Right. I am planning on allowing multiple layouts to switch between. I have a feeling allowing multiple pages like that can cause serious performance issues, especially if they run in a single browser window.

I suggest to use layouts (once those are implemented) and multiple browser tabs instead.
