### ISSUE TITLE
Oversized default emoteset.

### ISSUE THREAD

**Issue by Kanthes** [CBenni/mt2#21]
https://i.imgur.com/MSgBbxL.png

**Comment by CBenni** [comment]
Ive reduced the size of all emotes, I might have to look into what the correct sizes are, but I feel like theyre ok for now.

**Comment by arkham81a** [comment]
Uh. Make them a little bigger as now multipart emotes are very very bad looking. 
https://i.imgur.com/ysQ9NKj.png

**Comment by Kanthes** [comment]
Emotes should be 28x28, while standard emotes like :) should be 25x19 based on a screenshot I just took.
