### ISSUE TITLE
Chat not scrolling

### ISSUE THREAD

**Issue by arkham81a** [CBenni/mt2#22]
Mod Logs don't appear to scroll the chat downward whenever a new message pops up beneath it. The only way to unfreeze it is to freeze it with a hotkey/hover and then unfreeze it, it will then suddenly jump to the bottom. The Chat pausing indicator also does not show up.

Images and Console Errors below: 

https://i.imgur.com/wmdbqZg.jpg - Screenshot with Scroll bar highlighted

https://i.imgur.com/UNfHQuS.gifv - Gif of unpause

https://i.imgur.com/qU6mbzr.png - Only one Console Error

https://pastebin.com/nHbC73dX - Config

**Comment by arkham81a** [comment]
Update - More Console errors and it's also happening to the main chat tab. https://i.imgur.com/1CNeQoo.png

**Comment by arkham81a** [comment]
I'm changing the title to exclude Mod logs as now I'm seeing the same problem in more than Mod logs with different settings.  In this config I didn't have Cursor pausing enabled however when I put my cursor over chat it fixes itself. Also note the highlights updating in the top preset before I hovered over the main chat. (All these issues in the video are displayed on the right - Sodapoppin)

Video of the bug in action - https://streamable.com/jvufo
No console errors
Config - https://pastebin.com/0hHD2Jyt

**Comment by CBenni** [comment]
I have identified a seemingly unrelated issue and performed a few fixes that might help with chat scrolling not working (in my testing, it did)
Keep me updated on if https://github.com/CBenni/mt2/commit/dfa7c2321598d95a20b66b636034959357adf731 helps with the chat scrolling issues.
