### ISSUE TITLE
@ & emote completion not working

### ISSUE THREAD

**Issue by Decicus** [CBenni/mt2#45]
Seems to be a Firefox-only issue: https://i.decic.us/2018-04-22_AqM7bh.mp4

**Comment by DoctorWigglez** [comment]
Confirmed working on my end on Firefox 60.0b10 (64-bit).

: emotes and @ mentioning are popping up, tab and enter completes the selection and exits the box.

**Comment by Decicus** [comment]
Yep, can confirm it's working on my end as well.
