### ISSUE TITLE
Add ability to toggle individual buttons in settings

### ISSUE THREAD

**Issue by AlcaDesign** [CBenni/mt2#54]
Quick Photoshop edit:
![](https://alca.tv/static/u/20ee83b1-6d1f-47a7-884d-8974ef21f684.png)

**Comment by CBenni** [comment]
Fixed in https://github.com/CBenni/mt2/commit/47a7e70f0f4062964fff9386da681d6c6ea7c2ed

**Comment by DoctorWigglez** [comment]
Confirmed to be working. Tested all three available modes of an inline mod icon in channels with and without mod status.
