### ISSUE TITLE
Dragging chat sometimes can get stuck on cursor

### ISSUE THREAD

**Issue by LFQS0on** [CBenni/mt2#59]
Managed to replicate it by holding the chat for a bit and on mouse release, the window still doesn't drop. https://gyazo.com/2aef18a434de6e3ee95cd419812f1779

It was fixed again with a simple refresh.

**Comment by CBenni** [comment]
This is a known bug, but your description finally helped me figure out whats going on:
This happens whenever the channel list updates while you drag the item, destroying the drag source, making it impossible to be dropped!

I will do my best to fix that.
