### ISSUE TITLE
Custom extra mentions are not displayed in chat settings if imported config contains duplicated words

### ISSUE THREAD

**Issue by PacGamer** [CBenni/mt2#67]
Highlights still function as intended. Newly added words are not displayed either, but can be confirmed to have been added by exporting the new config.

Imported config: https://i.imgur.com/52z8Gmm.png
Error: https://i.imgur.com/hg39WBq.png
Chat settings: https://i.imgur.com/TOmwY6H.png

**Comment by DoctorWigglez** [comment]
Confirmed fixed, allowed two entries of the same highlight text.
