### ISSUE TITLE
Mod Logs overwrite goes back too far.

### ISSUE THREAD

**Issue by Kanthes** [CBenni/mt2#80]
![image](https://user-images.githubusercontent.com/10464554/39161774-a19d4d3e-4772-11e8-91e8-6580fe58618a.png)

In this scenario Ohiowrestler was timed out once at 3:47, but then again later at 3:50. Because the user had already been timed out before, Mod Logs simply overwrote the earlier timeout message to add "2 times". This should only happen if both actions were in the last 10-30 seconds.

**Comment by CBenni** [comment]
Thanks for the reminder, I forgot about this.
