### ISSUE TITLE
@mention highlights not working every odd line

### ISSUE THREAD

**Issue by teradw** [CBenni/mt2#86]
Other highlights seem to be working fine
![chrome_2018-04-24_18-56-32](https://user-images.githubusercontent.com/24725862/39202179-77bd17a4-47f1-11e8-8cd9-0e2a2bda3b62.png)

**Comment by teradw** [comment]
No, this issue is present without using any custom stylesheet and on default settings.

**Comment by teradw** [comment]
And correction to the original post, it looks like it's only when more @mention messages are in a row and not about lines being odd/even. Although this _seems_ inconsistent when messages aren't same

![image](https://user-images.githubusercontent.com/24725862/39240296-a4c9e032-4883-11e8-8a4a-ec9465785328.png)
![image](https://user-images.githubusercontent.com/24725862/39240780-16627f8c-4885-11e8-93f9-f7ebbf454f00.png)

**Comment by CBenni** [comment]
Fixed in https://github.com/CBenni/mt2/commit/aff158db6406a74ebc337660a4baaa8f2743207e
