### ISSUE TITLE
Fix seeing inline buttons for other mods when you are not the broadcaster

### ISSUE THREAD

**Issue by mattts1** [CBenni/mt2#89]
I don't think this should be an option.. No mod should see inline buttons for other mods or the broadcaster since clicking them doesn't actually do anything.

**Comment by CBenni** [comment]
The reason why I personally want buttons everywhere is because otherwise, the lines are misaligned. So if anything, this would be an option. I am mainly not sure about the wording in the settings.

**Comment by mattts1** [comment]
Ah, well yeah, I guess ill just add a fix for the misalignment to my custom css file..

**Comment by CBenni** [comment]
I will be adding this feature as a 4th option called "when bannable".

**Comment by CBenni** [comment]
Fixed in https://github.com/CBenni/mt2/commit/6222d96836430f54baf8484948d9de5881062d36

**Comment by ceriath** [comment]
"when bannable" does not apply to yourself if you are the broadcaster
