### ISSUE TITLE
Cheering doesnt work

### ISSUE THREAD

**Issue by mattts1** [CBenni/mt2#90]
I typed cheer1 into chat and it came through as plain text so no bits were actually cheered.

**Comment by AlcaDesign** [comment]
Cheering is not handled by IRC; it may not even be possible to implement. If a third party tool is able to spend a user's Bits then there's probably a flaw in Twitch's system.

**Comment by CBenni** [comment]
It is not possible to spend bits via 3rd party software other than extensions, so this cannot be implemented. Even if it could, I wouldn't feel comfortable writing code that spends user's money.

**Comment by mattts1** [comment]
Yeah I didnt really think about the logistics about it. I just tried and it didnt work so I thought I would report it.
